### ISSUE TITLE
Personaje por default

### ISSUE THREAD

**Issue by mauruch** [nmouteda/mk-tp-7542#10]
Si nos borra las sprites del personaje, debemos tener un "default".. El default va a ser una copia de subzero.

**Comment by nmouteda** [comment]
Valido si en base al nombre del personaje que recibo del json existe una carpeta con ese nombre para levantar sus sprites. Si el path a alguno de los sprites no existe tomo los sprites de la carpeta de nombre default. En este caso la carpeta default posee los sprites de subzero
