### ISSUE TITLE
Validaciones en el archivo de configuracion

### ISSUE THREAD

**Issue by mauruch** [nmouteda/mk-tp-7542#14]
"ventana": {
		"anchopx": 525,
		"altopx": fa,
		"ancho": fas
	},

ROMPE EL JUEGO, NO INICIA

**Comment by diego-serra** [comment]
eso es porque no hay personajje por defecto
el json valida bien, pero falla cuando va a cargar el personaje

**Comment by mauruch** [comment]
Dale, lo veo conjunto a lo del personje por default

**Comment by mauruch** [comment]
Esto quedo resuelto, sin embargo hay que crear un escenario por default copado
