### ISSUE TITLE
Posición del personaje - unidades logicas

### ISSUE THREAD

**Issue by luftwaffe1944** [nmouteda/mk-tp-7542#6]
La posición del personaje esta en pixeles, pasar a unidades lógicas.
En el drawFrame del texture manager hay que multiplicar por ratioX y ratioY
Revisar todos los metodos del personaje que usen posX y ajustar usando el ratio
Definir un mismo margen  tanto para el layerManager como para el Character sobre los bordes de la ventana.

**Comment by nmouteda** [comment]
ya esta
